const Portfolio_data =
[
  {
      "id": 1,
      "name": "",
      "title": "Buy & Sell used product",
    "one": "This application based on used Laptop selling. Buyer, Seller, Admin types of users can use this.",
    "two": "There are separated opportunity for related user.",
    "there": " Admin can make any seller an admin if he wants and seller can add a product and Add a payment",
    "four": "Also admin can delete a user. like buyer or seller",
    "five": "In this website only buyer can order product",
      "tech": "Technology Used: React JS, React Router, React Query, Stripe, Axios, Tailwind CSS, Daisy UI, Node JS, Express JS, MongoDB, Firebase Authentication, and other React Package.",
      "short": "              It is a website where you can buy and sell your used items! Here you can sell your used items.",
      "dp": "https://i.ibb.co/m0qzKTH/buysell.jpg",
      "img1": "https://i.ibb.co/pyVcXkv/screencapture-buy-and-sell-6fea0-web-app-2022-12-11-16-29-34.png",
      "img2": "https://i.ibb.co/ZL2wDBr/screencapture-buy-and-sell-6fea0-web-app-dashboard-all-User-2022-12-11-16-30-01.png",
      "img3": "https://i.ibb.co/MfqY72W/screencapture-buy-and-sell-6fea0-web-app-dashboard-all-Buyer-2022-12-11-16-30-26.png",
      "live": "https://buy-and-sell-6fea0.web.app/",
      "client": "https://github.com/leoarafat/buy-and-sell-client",
      "server": "https://github.com/leoarafat/buy-and-sell-server"
  },
  {
      "id": 2,
      "name": "",
      "title": "World wide photography",
    "one": "A single page Full-stack application for individual photographer containing the services he provides.",
    "two": "Users can post, delete, and update their reviews.",
    "there": "Firebase authentication and JWT are used for user authentication and user authorization.",
    "four": "User can review our photography service. if he/she can delete his/her review. they can can delete the review",
    "five": "Also you can add a new service",
      "tech": "Technology Used: JavaScript, React JS, Node JS, Express JS, MongoDB, REST API, Tailwind CSS, Firebase Auth.",
      "dp": "https://i.ibb.co/rMjD8tq/photography.jpg",
      "short": "A single page Full-stack application for individual photographer containing the services he provides.",
      "img1": "https://i.ibb.co/fnXbzkN/screencapture-world-wide-photography-web-app-my-Services-2022-12-11-16-28-31.png",
      "img2": "https://i.ibb.co/hRcJBFK/screencapture-world-wide-photography-web-app-2022-12-11-16-27-40-Copy.png",
      "img3": "https://i.ibb.co/DGts6Ld/screencapture-world-wide-photography-web-app-my-Review-2022-12-11-18-32-51.png",
      "live": "https://world-wide-photography.web.app/",
      "client": "https://github.com/leoarafat/worldwide-photography-client",
      "server": "https://github.com/leoarafat/worldwide-photography-server"
  },
  {
      "id": 3,
      "name": "",
      "title": "Programming Lab",
      "one": "This is a quality learning platform web application.",
      "two": "Learners can get their needed courses on this platform. Anyone can sign up for their profile and they, can visit the course outline.",
      "there": "But first you need to register",
      "four": "After login into this application, they can buy their needed course easily.",
      "five": "You can also download our course detail",
      "tech": "Technology Used: React JS, Tailwind CSS, Daisy UI, Firebase Auth, Firebase-Hosting, Node JS, and Express JS.",
      "dp": "https://i.ibb.co/XVQd3dt/codding.jpg",
      "short": "This is a quality learning platform web application. Learners can get their needed courses on this platform.",
      "img1": "https://i.ibb.co/FmX0SZZ/screencapture-programming-lab-a8dbb-web-app-detail-Page-05-2022-12-11-16-31-30.png",
      "img2": "https://i.ibb.co/WfQGP3J/screencapture-programming-lab-a8dbb-web-app-courses-2022-12-11-16-31-11.png",
      "img3": "https://i.ibb.co/xC60XJ1/screencapture-programming-lab-a8dbb-web-app-2022-12-11-16-30-51.png",
      "live": "https://programming-lab-a8dbb.web.app/",
      "client": "https://github.com/leoarafat/learning-plartform-client",
      "server": "https://github.com/leoarafat/learning-plartform-server"
  }
]
export default Portfolio_data
