const BlogApi = [
  {
    id: 1,
    image: "https://images.unsplash.com/photo-1661956600684-97d3a4320e45?ixlib=rb-4.0.3&ixid=MnwxMjA3fDF8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80",
    date: "2 May, 2021",
    title_one: "Digital Marketo to Their New Office.",
    desc_one: "Any marketing that uses electronic devices and can be used by marketing specialists to convey promotional messaging and measure its impact through your customer journey. In practice, digital marketing typically refers to marketing campaigns that appear on a computer, phone, tablet, or other device. It can take many forms, including online video",
    title_two: "Maximize your digital marketing Use Mailchimp",
    desc_two: "earch engine marketing, paid social ads and social media posts. Digital marketing is often compared to “traditional marketing” such as magazine ads, billboards, and direct mail. Oddly, television is usually lumped in with traditional marketing.",
    title_three: "A digital marketing strategy allows you to leverage",
    desc_three: "Did you know that more than 3 quarters of Americans go online on a daily basis? Not only that, but 43% go on more than once a day and 26% are online “almost constantly.”These figures are even higher among mobile internet users. 89% of Americans go online at least daily, and 31% are online almost constantly. As a marketer, it’s important to take advantage of the digital world with an online advertising presence, by building a brand, providing a great customer experience that also brings more potential customers and more, with a digital strategy.",
  },
  {
    id: 2,
    image: "https://images.unsplash.com/photo-1613909207039-6b173b755cc1?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=947&q=80",
    date: "28 April, 2021",
    title_one: "The services provide for design ",
    desc_one: "Considering the extent to which the service industry contributes to our GNP, very little has been said or written about the application of rational management techniques to the development of new services. Many believe that good service results from the style of an individual entrepreneur or company and is therefore highly idiosyncratic.",
    title_two: "Designing Services That Deliver",
    desc_two: "As a result of her years of experience with service organizations, Ms. Shostack thinks it’s time that managers subject service development to more rigorous analysis and control. This very pragmatic article describes how the use of a blueprint can help a service developer not only to identify problems before they happen but also to see the potential for other market opportunities. While the blueprint is most useful to managers developing new services, others can apply the same principles to test the quality of services for which they contract.",
    title_three: "Examples of poor service are widespread; in survey after survey.",
    desc_three: "We’re all familiar with the symptoms of service failure. Your shirt comes back from the laundry with a broken button. Within a week of paying an outrageous repair bill, that ominous rattle reappears in your car’s engine. A customer service representative says he’ll get back to you and doesn’t. An automatic teller swallows your card.",
  },
  {
    id: 3,
    image: "https://images.unsplash.com/photo-1628494391268-c9935bc384d5?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=830&q=80",
    date: "20 Jun, 2021",
    title_one: "Mobile app landing design & app maintain.",
    desc_one: "Imagine pointing the light on your phone at a locked door and having it click open. This may seem like something straight out of a science fiction movie, but this is a technology of today. BrightLock's mobile app makes it safe and secure to open smart lock doors at home and at work with a flick of your smartphone..",
    title_two: "From content structure to visual design elements",
    desc_two: "Knitting is a low-tech pursuit requiring only yarn, needles, and a whole lot of patience. Bellish brings tech to this creative pursuit with a mobile app that generates sweater patterns, color swatches, and other tools to help improve your knitting skills. This mobile app website created with Webflow is full of thoughtful design and a well-ordered organization to show how the app works..",
    title_three: "There are a few competing peer-to-peer payment apps out there.",
    desc_three: "From their gently stylized logo to the screenshots showing the simplicity of the Bellish app, the app landing page design has a softness to it. The user experience captures the feel of the relaxing pursuit of knitting. And it shows how the Bellish app can make the entire knitting process from pattern design to row counting an easier and more efficient experience.",
  },
]
export default BlogApi
